# Generated by Django 2.0.13 on 2019-03-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msn_number', models.CharField(db_index=True, max_length=100)),
                ('carrier_name', models.CharField(max_length=200)),
                ('capacity', models.CharField(db_index=True, max_length=100)),
                ('source_arrival_time', models.DateTimeField(db_index=True)),
                ('departure_time', models.DateTimeField(db_index=True)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('harness_length', models.IntegerField(default=0)),
                ('gross_weight', models.FloatField(max_length=200)),
                ('atmospheric_pressure', models.FloatField(max_length=200)),
                ('room_temperature', models.CharField(max_length=200)),
                ('fuel_capacity_on_left_wing', models.FloatField(max_length=200)),
                ('fuel_quantity_on_left_wing', models.FloatField(max_length=200)),
                ('fuel_capacity_on_right_wing', models.FloatField(max_length=200)),
                ('fuel_quantity_on_right_wing', models.FloatField(max_length=200)),
                ('flight_no', models.IntegerField(default=0)),
            ],
        ),
    ]
