# Generated by Django 2.0.13 on 2019-03-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='flight_no',
            field=models.CharField(max_length=200),
        ),
    ]
