# Generated by Django 2.0.13 on 2019-03-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190307_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='capacity',
            new_name='model',
        ),
    ]
