# Generated by Django 2.0.13 on 2019-03-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190307_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Country',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('USA', 'USA')], db_index=True, default='India', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='carrier_name',
            field=models.CharField(blank=True, choices=[('Indigo', 'Indigo'), ('JetAirways', 'JetAirways'), ('AirAsia', 'AirAsia'), ('SpiceJet', 'SpiceJet'), ('GoAir', 'GoAir')], db_index=True, default='India', max_length=100, null=True),
        ),
    ]
