# Generated by Django 2.0.13 on 2019-03-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190307_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='source_arrival_time',
            new_name='arrival_time',
        ),
        migrations.AlterField(
            model_name='info',
            name='destination',
            field=models.CharField(max_length=200, verbose_name='Destination Airport'),
        ),
        migrations.AlterField(
            model_name='info',
            name='source',
            field=models.CharField(max_length=200, verbose_name='Source Airport'),
        ),
    ]
